### ISSUE TITLE
Bitcoin::Crypto deprecation warnings

### ISSUE THREAD

**Issue by bbrtj** [refeco/Blockchain-Ethereum-Keystore#7]
Hello,

your distribution uses Bitcoin::Crypto as a dependency. There was a major release yesterday which deprecated some symbols. Your distribution is affected and is now issuing deprecation warnings (as intended): http://www.cpantesters.org/cpan/report/c3b27e02-6bd5-11ee-8e63-5ed96d8775ea

The deprecated methods are not going away for a long time, but you may want to upgrade the dependency to version `2.000` and modify your code accordingly. In your case, seems like it would involve changing `->to_hex` to `->to_serialized` (plus removing the pack function call, as `to_serialized` already returns a bytestring) and changing `->from_hex_seed($seed)` to `->from_seed([hex => $seed])`.

You can read more about new style of handling formats in Bitcoin::Crypto [in the manual](https://metacpan.org/dist/Bitcoin-Crypto/view/lib/Bitcoin/Crypto/Manual.pod#How-to-pass-data-to-functions?)

Cheers.

**Comment by regcostajr** [comment]
Hi @bbrtj, thanks for the heads up and for your hard work in Bitcoin::Crypto, this is fixed and released at https://github.com/refeco/Blockchain-Ethereum-Keystore/issues/7
